Fix `hgd` short-circuiting bugs for Misha.

diff --git a/dotfiles/bash_aliases b/dotfiles/bash_aliases
--- a/dotfiles/bash_aliases
+++ b/dotfiles/bash_aliases
@@ -61,33 +61,52 @@ if [[ -d "${WORKTREE_ROOT}" ]]; then
         cd "${WORKTREE_ROOT}"
         ls
     }
-    hgd() {
-        local worktree_path
+    hgd() { (
+        set -euox pipefail
         worktree_path="${WORKTREE_ROOT}/$1"
+        main_path="${WORKTREE_ROOT}/main"
+        requested_ref="refs/heads/$1"
+        main_ref="refs/heads/main"
         if [[ -d "${worktree_path}" ]]; then
-            echo "Worktree exists, taking you there!"
-            cd "${worktree_path}"
-            pwd
-        else
-            if git show-ref --verify --quiet "refs/heads/$1"; then
-                echo "Checking out existing branch...$1"
-                git worktree add "${worktree_path}" "$1" && cd "${worktree_path}"
-            else
-                echo "Pulling upstream changes to main before creating new branch!"
-                hgd main >/dev/null 2>&1 &&
-                    git pull upstream main &&
-                    git worktree add "${WORKTREE_ROOT}/$1" main -b "$1" &&
-                    cd "${worktree_path}"
-            fi
-            echo "Pulling/updating all submodules..." &&
-                git submodule update --init --recursive
-
-            echo "Kicking off some slow repository rules in the background..."
-            echo "..."
-            echo "...it may take up to 5min for these to finish!"
-            bazel build $INITIAL_TARGET >/dev/null 2>&1 &
+            echo "Worktree exists, taking you there!" &&
+                cd "${worktree_path}" &&
+                pwd
+            return $?
         fi
-    }
+        echo "Fetching 'origin' to ensure we know if the branch exists!" >/dev/null
+        git fetch origin
+        if git show-ref --verify --quiet "${requested_ref}"; then
+            echo "Checking out existing branch...$1" &&
+                git worktree add "${worktree_path}" "$1" &&
+                cd "${worktree_path}" &&
+                pwd
+            return $?
+        fi
+        if ! git show-ref --verify --quiet "${main_ref}"; then
+            echo "There does not seem to be a 'main' branch...please make one!" >/dev/null
+            return 1
+        fi
+        if [[ ! -d "${main_path}" ]]; then
+            echo "There does not appear to be a worktree for the main branch...please make one!" >/dev/null
+            return 2
+        fi
+        echo "Pulling upstream changes to main before creating new branch!" >/dev/null
+        if ! { cd "${main_path}" && git pull upstream main; }; then
+            echo "Failed to pull upstream changes to main, please update 'main' then re-run 'hgd'!" >/dev/null
+            return 3
+        fi
+        echo "Creating new worktree on fresh branch based on 'main'!" >/dev/null
+        if ! { git worktree add "${worktree_path}" main -b "$1" && cd "${worktree_path}"; }; then
+            echo "Failed to create worktree!" >/dev/null
+            return 4
+        fi
+        echo "Pulling/updating all submodules..." >/dev/null
+        git submodule update --init --recursive
+
+        echo "Kicking off some slow repository rules in the background..." >/dev/null
+        echo "...it may take up to 5min for these to finish!" >/dev/null
+        bazel build $INITIAL_TARGET >/dev/null 2>&1 &
+    ) }
     _exists_pr() {
         [[ "$#" -eq 2 ]] || return 255
         gh pr list --search "is:pr $2 head:$1" --json headRefName |
